server {
    listen 80;
    server_name wabro.propai.live;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.apk$ {
        add_header Content-Disposition 'attachment';
    }
}
